### ISSUE TITLE
Running this doesn't give the right output

### ISSUE THREAD

**Issue by p8tgames** [thebigmunch/audio-metadata#3]
I have set up this snippet right here (variation of example):
import audio_metadata
metadata = audio_metadata.load('Music.flac')
print(metadata)

And it only outputs this:

<FLAC ({
    'filepath': 'C:\\Users\\ptgms\\PycharmProjects\\medialibs\\Music.flac',
    'filesize': '30.30 MiB',
    'pictures': [

        })>,
    ],
    'seektable': <FLACSeekTable (26 seekpoints)>,

    })>,

    })>,
})>
I honestly have no idea why lmao
thanks for help

**Comment by p8tgames** [comment]
yeah sorry for formatting, best i can do lol

**Comment by thebigmunch** [comment]
You want to use a [fenced code block](https://github.github.com/gfm/#fenced-code-blocks) for formatting.  I can't tell at all what the output you're getting actually is. You'll also have to say what you'd expect and probably post the file for me to test.

**Comment by p8tgames** [comment]
File trying to run: https://del.dog/bikefoxuna
Output: https://del.dog/mabupixeni
I expected the results as shown in the example. The Media file has an Vorbis comments like album name, Artist, etc. 
I can uplaod the FLAC if needed.

**Comment by thebigmunch** [comment]
Please do, because that output doesn't look like something that's possible.

**Comment by p8tgames** [comment]
sorry, always try things out with meme songs xD
https://drive.google.com/open?id=15lkJXdYkh1M-4xdlQCcI5dijtlM5UJl2

**Comment by thebigmunch** [comment]
Loads perfectly fine here:

```
<FLAC ({
    'filepath': 'C:\\Users\\thebigmunch\\Downloads\\Music.flac',
    'filesize': '30.30 MiB',
    'pictures': [
        <VorbisPicture ({
            'colors': 0,
            'data': '77.06 KiB',
            'depth': 0,
            'description': '',
            'height': 640,
            'mime_type': 'image/jpeg',
            'type': <ID3PictureType.COVER_FRONT>,
            'width': 640,
        })>,
    ],
    'seektable': <FLACSeekTable (26 seekpoints)>,
    'streaminfo': <FLACStreamInfo ({
        'bit_depth': 16,
        'bitrate': '1009 Kbps',
        'channels': 2,
        'duration': '04:11',
        'md5': '777bd0eceb35920ca72d16c4b1ffb8d3',
        'sample_rate': '44.1 KHz',
    })>,
    'tags': <VorbisComment ({
        'album': ['Deja Vu (Initial D)'],
        'albumartist': ['Tsuko G.'],
        'artist': ['Tsuko G.'],
        'copyright': ['Tsuko Records'],
        'date': ['2017'],
        'discnumber': ['1'],
        'disctotal': ['1'],
        'isrc': ['QM2PV1715853'],
        'title': ['Deja Vu (Initial D)'],
        'tracknumber': ['1'],
        'tracktotal': ['1'],
        'upc': ['840094933231'],
    })>,
})>
```

**Comment by p8tgames** [comment]
i still get the weird output, weird. maybe i missed some dependency?

**Comment by thebigmunch** [comment]
I have no idea what is wrong on your system. All I can say is that it works on multiple systems I've tested on, so it's likely something on your end.
